from pathlib import Path
import subprocess
root=Path.cwd()
p=root/'index.html';s=p.read_text()
def replace(old,new,count=None):
 global s
 assert old in s,old[:100]
 s=s.replace(old,new) if count is None else s.replace(old,new,count)
replace('  function validateSave(raw){','  /* HOMETOWN_DRIVES_BEGIN */\n  /* HOMETOWN_DRIVES_END */\n  function validateSave(raw){')
replace('/* SESSION_SAVE_UI_BEGIN */','/* PRO_DRIVING_UI_BEGIN */\n/* PRO_DRIVING_UI_END */\n/* SESSION_SAVE_UI_BEGIN */')
replace('</style>','/* PRO_DRIVING_CSS_BEGIN */\n/* PRO_DRIVING_CSS_END */\n</style>',1)
replace('workshopMemories:WorkshopMemories.defaults(),vehicle:','workshopMemories:WorkshopMemories.defaults(),hometown:HometownDrives.defaults(),vehicle:')
replace('workshopMemories:WorkshopMemories.sanitize(raw.workshopMemories),vehicle:','workshopMemories:WorkshopMemories.sanitize(raw.workshopMemories),hometown:HometownDrives.sanitize(raw.hometown),vehicle:')
replace('ReleaseUX,SessionSaves};','ReleaseUX,SessionSaves,HometownDrives};')
replace("if(!hadSave){save.settings.weather='rain';","if(!hadSave){save.settings.weather='clear';save.climate.mode='clear';")
replace('initSessionSaves();applySettings();','initSessionSaves();initProDrive();applySettings();')
replace('echoDirector=nextEcho;','echoDirector=nextEcho;proWorldReady();',1)
replace('updateDriverState();releaseUpdateState();','updateDriverState();releaseUpdateState();proSyncState();')
replace('showState();audio.enabled=settings.sound;','showState();if(proGoal())proSyncGoal();audio.enabled=settings.sound;')
replace('tickEcho(C.DT);tickMemoryGhost','tickEcho(C.DT);proTick(C.DT);tickMemoryGhost')
replace('releaseUpdateHUD();drawMap();','releaseUpdateHUD();proHUD();drawMap();')
replace('function updateCamera(dt){\n',"function updateCamera(dt){\n if(state==='photo'){proPhotoCamera();return;}\n")
replace('||echoObjective()?.destination;\n if(!cp', '||echoObjective()?.destination||proGoal()||(sim.world.northBerwick?uxDestination:null);\n if(!cp')
replace('||passengerObjective()?.destination||null;renderer.update(sim,dt,weatherRenderSettings());',"||passengerObjective()?.destination||proGoal()||null;renderer.update(sim,state==='photo'?0:dt,weatherRenderSettings());")
replace('resolutionScale:renderer.scale,storageAvailable,release:','resolutionScale:renderer.scale,storageAvailable,pro:proSnapshot(),release:')
replace("function resume(){if(state!=='pause')return;","function resume(){if(state!=='pause'||renderer.contextLost||document.querySelector('dialog[open]'))return;")
replace('function frame(timestamp){\n try{','function frame(timestamp){\n try{\n  if(renderer.contextLost){input.clear();input.blocked=true;lastFrame=timestamp;accumulator=0;requestAnimationFrame(frame);return;}')
replace('this.contextLost=false;this.contextEpoch=0;this.contextLosses=0;','this.contextLost=false;this.contextEpoch=this.contextEpoch||1;this.contextLosses=0;')
replace("'webglcontextrestored',()=>{try{this.initGL();","'webglcontextrestored',()=>{try{this.releaseForgetGL();this.initGL();")
replace(' releaseDisposeGL(){const gl=this.gl;'," releaseForgetGL(){for(const key of ['p','probeProgram','sky','shadowProgram','bloomProgram','postProgram','envTex','studioTex','storyTex','atlasTex','townTex'])this[key]=null;this.targets=null;this.probeBuffers=[];this.shadowTarget=null;this.msaa=null;this.batches={};}\n releaseDisposeGL(){const gl=this.gl;")
replace('resize(){if(!this.gl)return super.resize();const w=','resize(){if(!this.gl)return super.resize();if(this.gl.isContextLost())return;const w=')
replace("'reborn-vehicle-model-ready',()=>{if(renderer.gl)","'reborn-vehicle-model-ready',()=>{if(renderer.gl&&!renderer.contextLost&&!renderer.gl.isContextLost())")
s=s.replace('0.16.0-graphics-recovery-p019','0.29.0-hometown-drives-p032').replace('BUILD 019','BUILD 032').replace('Build 019','Build 032').replace('/ 014 · PASSENGER DRIVES','/ 032 · HOMETOWN DRIVES')
p.write_text(s)
p=root/'tools/sync-town.cjs';s=p.read_text().replace("of [['session-saves'","of [['hometown-drives','HOMETOWN_DRIVES','  '],['pro-driving-ui','PRO_DRIVING_UI',''],['pro-driving-ui','PRO_DRIVING_CSS','','css'],['session-saves'");p.write_text(s)
p=root/'src/driver-ux.js';s=p.read_text().replace("document.addEventListener('keydown',e=>{const id=","document.addEventListener('keydown',e=>{if(document.querySelector('dialog[open]'))return;const id=");p.write_text(s)
p=root/'src/release-ux.js';s=p.read_text().replace('function releaseSafeUpdate(){return ','function releaseSafeUpdate(){return !graphicsInterruption&&!proDirector?.state.active&&').replace('if(document.hidden){releaseSkippedFrames++;return false;}','if(document.hidden||renderer.contextLost){releaseSkippedFrames++;return false;}').replace("const cap=(state==='play'","const cap=state==='photo'?30:(state==='play'").replace('return {build:18,','return {build:32,');p.write_text(s)
subprocess.run(['node','tools/bundle.cjs'],check=True)
