'use strict';
// Executes the shipped core and canonical town, not a parallel simulation.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'),html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const scripts=[...html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi)].map(m=>m[1]),box=vm.createContext({console});
vm.runInContext(scripts.find(s=>s.includes('else root.RebornCore = api')),box);
const C=box.RebornCore,E=C.EchoRoads,world=C.createNorthBerwickWorld(JSON.parse(fs.readFileSync(path.join(root,'assets/worlds/north-berwick/world.json'))));
const clone=x=>JSON.parse(JSON.stringify(x)),fresh=s=>new E.Director(s,world),car=p=>({...p,yaw:p.yaw||0,vx:0,vz:0}),context=p=>({available:true,running:true,car:car(p),passenger:false});
let tests=0;const test=(n,f)=>{f();tests++;console.log('PASS Echo Roads: '+n);};
function tick(d,p,n=200,extra={}){for(let i=0;i<n;i++)d.tick(C.DT,{...context(p),...extra});}
function view(d,id,era){d.focus(id);d.state.targetEra=era;tick(d,d.anchors.find(a=>a.id===id).point,520);assert.equal(d.state.visits[id][era],true);}
function both(d,id){view(d,id,'present');view(d,id,'memory');}
function all(d){for(const a of E.ANCHORS){both(d,a.id);assert.equal(d.remember(a.id,'quiet').ok,true);}}

test('six bounded public landmark memories with explicit interpretation labels',()=>{assert.equal(E.ANCHORS.length,6);assert.equal(new Set(E.ANCHORS.map(a=>a.id)).size,6);assert.equal(E.LIMITS.anchors,6);for(const a of E.ANCHORS)assert.ok(a.present&&a.memory&&a.prop);assert.match(html,/not an exact historical reconstruction/);});
test('v1 save migration keeps mechanics, trust, passenger, road and journal data',()=>{const old=C.validateSave({version:1,bestRun:42,vehicle:{fuel:37,odometerMiles:500},town:{trust:68},roadKnowledge:{'Elm Street':{distanceM:250}},journeys:{completed:['long-way-home']},journal:[{kind:'passenger',reason:'Ride'}]});assert.equal(old.version,1);assert.equal(old.vehicle.fuel,37);assert.equal(old.vehicle.odometerMiles,500);assert.equal(old.town.trust,68);assert.equal(old.roadKnowledge['Elm Street'].distanceM,250);assert.equal(old.journeys.completed.length,1);assert.equal(old.echoes.active,false);assert.equal(old.journal.length,1);});
test('non-finite and oversize state is sanitized; unknown prototype IDs ignored',()=>{const visits={};for(let i=0;i<1000;i++)visits['fake'+i]={present:true,memory:true,choice:'place'};visits['town-office-police']={present:true,memory:false,choice:'place',at:Infinity};const s=E.sanitize({active:true,targetEra:'future',blend:NaN,elapsed:Infinity,distanceM:-100,focus:'__proto__',lastPosition:{x:Infinity,z:0,yaw:0},visits,history:Array(1000).fill({id:'__proto__',choice:'place'}),completed:true});assert.equal(s.targetEra,'present');assert.equal(s.blend,0);assert.equal(s.elapsed,0);assert.equal(s.distanceM,0);assert.equal(s.lastPosition,null);assert.equal(Object.keys(s.visits).length,1);assert.equal(s.visits['town-office-police'].choice,'');assert.equal(s.history.length,0);assert.equal(s.completed,false);assert.equal(Object.prototype.polluted,undefined);});
test('inactive imported sessions cannot leave a visual layer enabled',()=>{const s=E.sanitize({active:false,blend:1,targetEra:'memory'});assert.equal(s.blend,0);assert.equal(s.targetEra,'present');});
test('all six anchors project onto maintained street frontages, not nearest unrelated lanes',()=>{const d=fresh();assert.equal(d.anchors.length,6);for(const a of d.anchors){assert.equal(a.point.road,a.building.frontRoad);assert.ok(a.point.distanceFromLandmark<=160);const near=C.nearestRoad(world,a.point.x,a.point.z);assert.ok(near.distance<.01);assert.ok(Number.isFinite(a.point.yaw));}assert.equal(d.anchors[0].point.road,'Main Street');});
test('all six observation points stay stationary against production building collisions',()=>{const d=fresh();for(const a of d.anchors){assert.ok(E.roadPointClear(world,a.point),a.id);const c=C.createCar(a.point.x,a.point.z,a.point.yaw);for(let i=0;i<180;i++)C.stepCar(c,{throttle:0,brake:0,steer:0},world);assert.ok(Math.hypot(c.x-a.point.x,c.z-a.point.z)<.01,a.id);assert.equal(c.health,100);}});
test('the mill frontage avoids its broad collision hull without modifying the map',()=>{const bad={x:3761.3324487211453,z:4237.198469275297,yaw:3.018294204391599};assert.equal(E.roadPointClear(world,bad),false);assert.equal(fresh({active:true,lastPosition:bad}).state.lastPosition,null);const a=fresh().anchors.find(a=>a.id==='olde-woolen-mill');assert.equal(a.point.road,'Canal Street');assert.ok(Math.hypot(a.point.x-bad.x,a.point.z-bad.z)>3);assert.ok(a.point.distanceFromLandmark<55);});
test('legitimate car positions resolved next to a wall survive reload',()=>{const c=C.createCar(3761.3324487211453,4237.198469275297,0);C.stepCar(c,{},world);const loaded=fresh({active:true,lastPosition:c});assert.ok(loaded.state.lastPosition);assert.equal(loaded.state.lastPosition.x,c.x);assert.equal(loaded.state.lastPosition.z,c.z);});
test('incomplete or missing North Berwick frontage fails a launch cleanly',()=>{const d=new E.Director(null,{...world,buildings:[]});assert.equal(d.begin().ok,false);assert.equal(d.state.active,false);assert.equal(E.bind({northBerwick:false}).length,0);});
test('passenger commitments prevent Echo launch',()=>{const d=fresh();assert.equal(d.begin(true).ok,false);assert.equal(d.state.active,false);assert.equal(d.begin().ok,true);});
test('V compare requires an enabled active session',()=>{const d=fresh();assert.equal(d.toggle(),false);d.begin();assert.equal(d.toggle(),false);tick(d,d.anchors[0].point,1);assert.equal(d.toggle(),true);assert.equal(d.state.targetEra,'memory');});
test('blend moves gradually and remains bounded across many comparisons',()=>{const d=fresh();d.begin();tick(d,d.anchors[0].point,1);d.toggle();tick(d,d.anchors[0].point,60);assert.ok(d.state.blend>0&&d.state.blend<1);for(let i=0;i<20;i++){d.toggle();tick(d,d.anchors[0].point,500);assert.ok(d.state.blend>=0&&d.state.blend<=1);}});
test('paused map/hub and invalid elapsed steps freeze ALL memory state',()=>{const d=fresh();d.begin();tick(d,d.anchors[0].point,4);d.toggle();const before=clone(d.state);tick(d,d.anchors[0].point,100,{running:false});for(const dt of [NaN,Infinity,-1,0,2])d.tick(dt,context(d.anchors[0].point));assert.deepEqual(clone(d.state),before);});
test('outside Free Drive and with a passenger both disable visuals and simulation',()=>{const d=fresh();d.begin();both(d,E.ANCHORS[0].id);const before=clone(d.state);tick(d,d.anchors[0].point,50,{available:false});assert.equal(d.enabled,false);assert.equal(d.mix(d.anchors[0].point),0);assert.deepEqual(clone(d.state),before);tick(d,d.anchors[0].point,50,{passenger:true});assert.equal(d.enabled,false);assert.deepEqual(clone(d.state),before);});
test('reduced motion changes the layer without a transition animation',()=>{const d=fresh();d.begin();tick(d,d.anchors[0].point,1);d.toggle();tick(d,d.anchors[0].point,1,{reducedMotion:true});assert.equal(d.state.blend,1);});
test('driving too fast cannot collect a viewpoint or complete dwell',()=>{const d=fresh();d.begin();const p=d.anchors[0].point;d.tick(C.DT,context(p));for(let i=0;i<200;i++){const moving={...p,x:p.x+(i%2?.2:0)};d.tick(C.DT,context(moving));}assert.equal(d.state.visits[p.id],undefined);tick(d,p,50);d.tick(C.DT,context({...p,x:p.x+.2}));assert.equal(d.dwell.seconds,0);});
test('stale internal velocity cannot block a physically stationary observation',()=>{const d=fresh();d.begin();const p=d.anchors[0].point;tick(d,p,200,{car:{...car(p),vx:12,vz:-8}});assert.equal(d.state.visits[p.id].present,true);});
test('brief fly-bys do not count, slow observations do',()=>{const d=fresh();d.begin();const p=d.anchors[0].point;tick(d,p,60);assert.equal(d.state.visits[p.id],undefined);tick(d,p,150);assert.equal(d.state.visits[p.id].present,true);});
test('transitioning between eras never grants an observation early',()=>{const d=fresh();d.begin();tick(d,d.anchors[0].point,200);d.toggle();tick(d,d.anchors[0].point,100);assert.equal(d.state.visits[E.ANCHORS[0].id].memory,false);tick(d,d.anchors[0].point,500);assert.equal(d.state.visits[E.ANCHORS[0].id].memory,true);});
test('focused landmark is used when two observation radii overlap',()=>{const d=fresh();d.begin();const a=d.anchors[0],b=d.anchors[2],p={x:(a.point.x+b.point.x)/2,z:(a.point.z+b.point.z)/2,yaw:0};d.focus(a.id);assert.equal(d.nearest(p).id,a.id);d.focus(b.id);assert.equal(d.nearest(p).id,b.id);});
test('both viewpoints are mandatory before choosing a reflection',()=>{const d=fresh();d.begin();const id=E.ANCHORS[0].id;assert.equal(d.remember(id,'place').ok,false);view(d,id,'present');assert.equal(d.remember(id,'place').ok,false);view(d,id,'memory');assert.equal(d.remember(id,'unknown').ok,false);assert.equal(d.remember(id,'place').ok,true);});
test('all three reflection choices persist and repeated clicks cannot farm entries',()=>{for(const choice of Object.keys(E.CHOICES)){const d=fresh();d.begin();const id=E.ANCHORS[0].id;both(d,id);d.takeEvents();d.remember(id,choice);assert.equal(d.state.visits[id].choice,choice);assert.equal(d.takeEvents().filter(e=>e.type==='remembered').length,1);assert.equal(d.remember(id,choice).ok,false);assert.equal(d.takeEvents().length,0);assert.equal(fresh(clone(d.state)).state.visits[id].choice,choice);}});
test('one six-place ending requires returning to Today and never repeats',()=>{const d=fresh();d.begin();all(d);assert.equal(d.state.completed,false);d.takeEvents();d.state.targetEra='present';tick(d,{x:0,z:0,yaw:0},400);assert.equal(d.state.completed,true);assert.equal(d.objective().destination,null);assert.equal(d.objective().title,'Every road remembers.');assert.equal(d.takeEvents().filter(e=>e.type==='complete').length,1);tick(d,d.anchors[0].point,400);assert.equal(d.takeEvents().filter(e=>e.type==='complete').length,0);const re=fresh(clone(d.state));tick(re,re.anchors[0].point,400);assert.equal(re.takeEvents().filter(e=>e.type==='complete').length,0);});
test('reload retains viewpoint, destination, pose, era and comparison progress',()=>{const d=fresh();d.begin();both(d,E.ANCHORS[2].id);d.remember(E.ANCHORS[2].id,'feeling');d.focus(E.ANCHORS[4].id);const loaded=fresh(clone(d.state));assert.deepEqual(clone(loaded.state),clone(d.state));tick(d,d.anchors[0].point,250);tick(loaded,loaded.anchors[0].point,250);assert.deepEqual(clone(loaded.state),clone(d.state));});
test('unsafe imported respawn locations are discarded',()=>{const d=fresh({active:true,lastPosition:{x:500000,z:500000,yaw:0}});assert.equal(d.state.lastPosition,null);});
test('ending keeps discoveries but restores Today and removes props',()=>{const d=fresh();d.begin();both(d,E.ANCHORS[0].id);d.remember(E.ANCHORS[0].id,'quiet');d.end();assert.equal(d.state.active,false);assert.equal(d.state.blend,0);assert.equal(d.state.visits[E.ANCHORS[0].id].choice,'quiet');assert.equal(d.props(d.anchors[0].point).length,0);});
test('memory layer fades outside corridor without altering discovered history',()=>{const d=fresh();d.begin();view(d,E.ANCHORS[0].id,'memory');assert.equal(d.mix(d.anchors[0].point),1);assert.equal(d.mix({x:0,z:0}),0);assert.equal(d.props({x:0,z:0}).length,0);});
test('all placed props are finite, bounded, road-safe, dry and cacheable',()=>{const d=fresh();d.begin();for(const a of d.anchors){view(d,a.id,'memory');const props=d.props(a.point);assert.ok(props.length>0);assert.ok(props.length<=E.LIMITS.props);for(const p of props){assert.ok(E.placementValid(world,p));assert.ok(p.h>0);}assert.equal(d.props(a.point),props);}const bad={x:world.spawn.x,z:world.spawn.z,y:1,yaw:0,w:5,h:2,d:5};assert.equal(E.placementValid(world,bad),false);assert.equal(E.placementValid(world,{...bad,x:NaN}),false);});
test('facade recoloring tags do not mutate geometry or source colors',()=>{const a=fresh().anchors[0],b=a.building,o={x:b.x,y:4,z:b.z,radius:1,color:[.6,.5,.4,1],surface:[0],m:[1,0,0,0]};const old=clone(o);E.markStatics([o],world);assert.ok(o.echoTone);assert.deepEqual(o.color,old.color);assert.deepEqual(o.m,old.m);assert.equal(o.x,old.x);});
test('simulation event queues and imported histories remain bounded',()=>{const d=fresh();d.begin();for(let i=0;i<1000;i++)d.focus(E.ANCHORS[i%6].id);assert.equal(d.events.length,E.LIMITS.events);const raw={active:true,elapsed:1000,visits:{},history:[]};for(const a of E.ANCHORS){raw.visits[a.id]={present:true,memory:true,choice:'quiet'};for(let i=0;i<100;i++)raw.history.push({id:a.id,choice:'quiet',at:i});}assert.ok(E.sanitize(raw).history.length<=6);});
test('Echo journal entries survive the existing save sanitation',()=>{const s=C.validateSave({version:1,journal:[{id:'echo-1',kind:'echo',mode:'free',world:'North Berwick',reason:'Every road remembers',miles:1}]});assert.equal(s.journal[0].kind,'echo');});
test('300 resumed loops produce identical bounded state and no extra completed rewards',()=>{const run=()=>{let d=fresh();d.begin();all(d);d.state.targetEra='present';tick(d,d.anchors[0].point,400);for(let i=0;i<300;i++){d=fresh(clone(d.state));d.begin();const a=d.anchors[i%6];d.focus(a.id);tick(d,a.point,4);d.toggle();tick(d,a.point,12);d.remember(a.id,'place');d.end();}return clone(d.state);};const a=run(),b=run();assert.deepEqual(a,b);assert.ok(JSON.stringify(a).length<5000);assert.equal(a.history.length,6);assert.equal(a.completed,true);});
test('canonical world, MkIV and legacy checkpoint remain byte-identical',()=>{const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(path.join(root,p))).digest('hex');assert.equal(hash('assets/worlds/north-berwick/world.json'),'8588954fcc6ed3c88a7336c89ea36e65213a7561e8c7a9dfdb7ad3bb7c4d0b52');assert.equal(hash('assets/vehicles/jetta-mkiv/volkswagen-bora-jetta-mk4-2005.cc-by-4.0.glb'),'ac9f1d907807e5cdb0cb02beeb676f2f4ebe6c53f363d5fec3cbe183604d2e3f');const cp=require('node:child_process');const legacy='legacy/99-5-REBORN-Build-004-PLAY.html';const source=cp.execFileSync('git',['show','708ce1719d4ca66efbc09e2e857245757fcf372c:'+legacy],{cwd:root,maxBuffer:5000000});assert.equal(hash(legacy),crypto.createHash('sha256').update(source).digest('hex'));});
console.log(JSON.stringify({pass:6,tests,anchors:6,repeatRuns:2,loopsPerRun:300,immutableAssets:'unchanged'}));
