'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),html=fs.readFileSync(path.join(root,'index.html'),'utf8'),box=vm.createContext({console});
vm.runInContext([...html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi)].map(x=>x[1]).find(x=>x.includes('else root.RebornCore = api')),box);
const C=box.RebornCore,H=C.HometownDrives,clone=x=>JSON.parse(JSON.stringify(x));let checks=0;
function test(name,fn){fn();checks++;console.log('PASS hometown drives: '+name);}
const raw=JSON.parse(fs.readFileSync(path.join(root,'assets/worlds/north-berwick/world.json'),'utf8')),world=C.createNorthBerwickWorld(raw),router=new C.ReleaseUX.Router(world),routes=H.catalog(world,router);
function parked(g){return {...g,vx:0,vz:0};}
function dwell(d,car,n=100,onRoad=true){let event;for(let i=0;i<n;i++)event=d.tick(C.DT,car,true,onRoad)||event;return event;}
test('all three itineraries connect all four roadside stops in the actual bundled town',()=>{assert.equal(routes.length,3);for(const r of routes){assert.ok(r.available);assert.equal(r.stops.length,4);assert.ok(r.distanceM>500);for(const p of r.stops){assert.ok(C.roadAt(world,p.x,p.z,2));assert.ok(Number.isFinite(p.approachM));}}});
test('lengths match the canonical road graph, not invented travel durations',()=>{assert.deepEqual(clone(routes.map(r=>Math.round(r.distanceM))),[1352,2945,13904]);});
test('old saves gain an empty optional itinerary without losing vehicle or story',()=>{const s=C.validateSave({version:1,vehicle:{fuel:43,odometerMiles:995},bestRun:50});assert.equal(s.vehicle.fuel,43);assert.equal(s.bestRun,50);assert.deepEqual(clone(s.hometown),clone(H.defaults()));});
test('unknown IDs, NaN and oversized fields cannot grow serialized progress',()=>{const s=H.sanitize({active:{id:'unknown',index:0},completed:{bad:{runs:20},'mill-main':{runs:Infinity,seconds:-2}},visited:Array(10000).fill('hurd-manor').concat('x')});assert.equal(s.active,null);assert.equal(s.visited.length,1);assert.equal(Object.keys(s.completed).length,1);assert.ok(JSON.stringify(s).length<300);});
test('wrong active indices are rejected',()=>{for(const index of [-1,4,1.2,'2',Infinity])assert.equal(H.sanitize({active:{id:'mill-main',index}}).active,null);});
test('starting an itinerary does not move or take control of a vehicle',()=>{const d=new H.Director(null,routes),car=parked(world.spawn),old=clone(car);assert.ok(d.begin('mill-main'));assert.deepEqual(clone(car),old);assert.equal(d.state.active.index,0);});
test('an unfinished itinerary is not silently replaced',()=>{const d=new H.Director(null,routes);d.begin('mill-main');assert.equal(d.begin('everyday'),false);assert.equal(d.begin('mill-main'),true);});
test('passing a stop at driving speed does not collect it',()=>{const d=new H.Director(null,routes);d.begin('mill-main');assert.equal(dwell(d,{...d.goal(),vx:9,vz:0},100),undefined);assert.equal(d.state.active.index,0);});
test('only a slow on-road dwell collects a stop',()=>{const d=new H.Director(null,routes);d.begin('mill-main');assert.equal(dwell(d,parked(d.goal()),100,false),undefined);const e=dwell(d,parked(d.goal()));assert.equal(e.type,'stop');assert.equal(d.state.active.index,1);});
test('pause freezes all itinerary distance and time and clears the arrival dwell',()=>{const d=new H.Director(null,routes);d.begin('mill-main');const car=parked(d.goal());dwell(d,car,10);const old=clone(d.state);for(let i=0;i<100;i++)d.tick(C.DT,car,false,true);assert.deepEqual(clone(d.state),old);assert.equal(d.dwell,0);});
test('a recovery jump does not count phantom road distance',()=>{const d=new H.Director(null,routes);d.begin('mill-main');d.tick(C.DT,parked(world.spawn),true,true);d.tick(C.DT,parked(d.goal()),true,true);assert.equal(d.state.active.distanceM,0);assert.equal(d.dwell,0);});
test('all itineraries complete with a bounded badge and four visited places',()=>{for(const r of routes){const d=new H.Director(null,routes);d.begin(r.id);let e;for(let i=0;i<4;i++)e=dwell(d,parked(d.goal()),110);assert.equal(e.type,'complete');assert.equal(d.state.active,null);assert.equal(d.state.completed[r.id].runs,1);assert.equal(d.state.visited.length,4);}});
test('completed and in-progress records round-trip through actual save and export sanitation',()=>{const d=new H.Director(null,routes);d.begin('mill-main');dwell(d,parked(d.goal()));const s=C.validateSave({version:1,hometown:clone(d.state)});assert.equal(s.hometown.active.index,1);const backup=C.ReleaseUX.backup(JSON.stringify({format:'REBORN_BACKUP_V1',save:s,story:null}));assert.equal(backup.save.hometown.active.index,1);});
test('ending an itinerary retains completed stamps',()=>{const d=new H.Director({completed:{'mill-main':{runs:2,distanceM:1300,seconds:200}}},routes);d.begin('long-way');d.end();assert.equal(d.state.completed['mill-main'].runs,2);});
test('missing mapped stop fails closed instead of drawing a fake route',()=>{const r=H.catalog({...world,landmarks:[]},router);assert.ok(r.every(x=>!x.available));assert.equal(new H.Director(null,r).begin('mill-main'),false);});
test('photo mode and graphics loss have explicit frame and update guards',()=>{assert.match(html,/if\(state==='photo'\)\{proPhotoCamera\(\);return;/);assert.match(html,/if\(renderer.contextLost\)\{input.clear/);assert.match(html,/releaseForgetGL\(\);this.initGL\(\)/);assert.match(html,/!graphicsInterruption&&!proDirector\?\.state.active/);assert.match(html,/x.drawImage\(source/);});
console.log(JSON.stringify({hometownChecks:checks,routeLengthsM:routes.map(r=>({id:r.id,metres:Math.round(r.distanceM)})),completionTest:'deterministic fixed-step fixtures; not an owner-driven road survey'}));
