'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'),html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const scripts=[...html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi)].map(m=>m[1]),context=vm.createContext({console});
vm.runInContext(scripts.find(s=>s.includes('else root.RebornCore = api')),context);const C=context.RebornCore,W=C.MaineWeather,T=C.Town,clone=x=>JSON.parse(JSON.stringify(x));
const world=C.createNorthBerwickWorld(JSON.parse(fs.readFileSync(path.join(root,'assets/worlds/north-berwick/world.json'),'utf8')));
const town={day:0,minuteOfDay:480,seed:995},make=(raw=null,t=town)=>new W.Director(raw,world,t);let tests=0;
function test(name,fn){fn();tests++;console.log('PASS weather: '+name);}
function bounded(d){const s=d.state;assert.ok(Object.keys(s.zones).length<=256);assert.ok(s.observations.length<=160);assert.ok(s.history.length<=32);assert.ok(JSON.stringify(s).length<150000);for(const z of Object.values(s.zones))for(const [k,v] of Object.entries(z)){assert.ok(Number.isFinite(v),k);if(k!=='lastService')assert.ok(v>=0&&v<=1,k);}}
test('version-1 save migrates without loss of mechanics, town, or journal',()=>{const s=C.validateSave({version:1,bestRun:63,vehicle:{fuel:37,odometerMiles:450},town:{...T.defaults(),trust:74},roadKnowledge:{'Elm Street':{distanceM:123}},journal:[{kind:'drive',miles:1}],stats:{trips:2}});assert.equal(s.bestRun,63);assert.equal(s.vehicle.fuel,37);assert.equal(s.town.trust,74);assert.equal(s.roadKnowledge['Elm Street'].distanceM,123);assert.equal(s.journal.length,1);assert.equal(s.climate.mode,'dynamic');assert.equal(s.version,1);});
test('malformed weather, duplicate observations, prototype keys and huge values are sanitized',()=>{const s=W.sanitize(JSON.parse('{"schemaVersion":1,"mode":"bad","seasonBase":"hack","cursor":-99,"zones":{"__proto__":{"polluted":1},"Main Street":{"ice":9,"salt":-2}},"observations":[{"road":"Main Street","hazard":"black-ice","at":9999999},{"road":"Main Street","hazard":"wet"}]}'),480);assert.equal(s.mode,'dynamic');assert.equal(s.cursor,0);assert.equal(s.zones['Main Street'].ice,1);assert.equal(s.zones['Main Street'].salt,0);assert.equal(s.observations.length,1);assert.equal(s.observations[0].at,480);assert.equal(Object.prototype.polluted,undefined);assert.ok(!Object.hasOwn(s.zones,'__proto__'));assert.equal(W.sanitize({schemaVersion:1,cursor:Infinity}).cursor,96);});
test('constructor binds only real named-road zones and caps imported state',()=>{const raw=W.defaults();raw.zones.Phantom=W.emptyZone();const d=make(raw);assert.ok(!Object.hasOwn(d.state.zones,'Phantom'));assert.ok(d.profiles.size>50);bounded(d);});
test('same seed, state and elapsed town time give identical weather',()=>{const a=make(),b=make();for(let t=485;t<=800;t+=5){a.advanceTo(t);b.advanceTo(t);}assert.deepEqual(clone(a.state),clone(b.state));});
test('weather evolution is independent of rendering-step partition',()=>{const a=make(),b=make();for(let t=481;t<=900;t++)a.advanceTo(t);for(let t=485;t<=900;t+=5)b.advanceTo(t);assert.deepEqual(clone(a.state),clone(b.state));});
test('mid-drive reload preserves surfaces and subsequent evolution',()=>{const a=make();a.advanceTo(612);const b=make(clone(a.state),{...town,minuteOfDay:612});assert.deepEqual(clone(a.state),clone(b.state));for(let t=615;t<=1000;t+=5){a.advanceTo(t);b.advanceTo(t);}assert.deepEqual(clone(a.state),clone(b.state));});
test('different seeds vary natural forecasts',()=>{const a=W.defaults(480,1),b=W.defaults(480,2);assert.notDeepEqual(clone(W.forecast(a,700)),clone(W.forecast(b,700)));});
test('paused clock, backwards time, NaN and Infinity never advance weather',()=>{const a=make(),before=JSON.stringify(a.state);for(const t of [NaN,Infinity,1])a.advanceTo(t);a.advanceTo(900,false);assert.equal(JSON.stringify(a.state),before);});
test('all seasonal and selected scenarios have coherent precipitation temperatures',()=>{const d=make();for(const season of W.SEASONS)for(const kind of W.KINDS){assert.ok(d.select(kind,season));const w=d.current;assert.ok([w.tempC,w.rain,w.snow,w.sleet,w.freezing,w.daylight].every(Number.isFinite));assert.ok([w.rain,w.snow,w.sleet,w.freezing].filter(n=>n>0).length<=1);if(w.snow)assert.ok(w.tempC<0);if(w.rain)assert.ok(w.tempC>=3);if(w.freezing)assert.ok(w.tempC<0);bounded(d);}assert.equal(d.select('hack','winter'),false);});
test('season cycle is deterministic and daylight follows town time',()=>{const s=W.defaults();assert.equal(W.seasonAt(s,0),'autumn');assert.equal(W.seasonAt(s,30*1440),'winter');assert.equal(W.seasonAt(s,120*1440),'autumn');assert.equal(W.forecast(s,0).daylight,0);assert.ok(W.forecast(s,720).daylight>.8);});
test('rain accumulates water according to drainage',()=>{const d=make();d.select('heavy-rain','summer');const low=W.emptyZone(),high=W.emptyZone(),w=d.current;for(let t=5;t<=180;t+=5){W.evolve(low,{shade:.4,drainage:.3,priority:3,phase:0},w,5,t);W.evolve(high,{shade:.4,drainage:.95,priority:3,phase:0},w,5,t);}assert.ok(low.wet>.8);assert.ok(low.puddle>high.puddle+.2);});
test('wet autumn leaves reduce traction',()=>{const d=make();d.select('rain','autumn');const z={...W.emptyZone(),wet:.8,leaves:.9};assert.equal(W.condition(z,d.current).hazard,'wet-leaves');assert.ok(W.condition(z,d.current).grip<.7);});
test('water freezes below zero and salt moderates freezing',()=>{const d=make();d.select('frost','winter');const w={...d.current,tempC:-2},a={...W.emptyZone(),wet:.9},b={...a,salt:1},p={shade:.6,drainage:.4,priority:3,phase:0};for(let t=5;t<=45;t+=5){W.evolve(a,p,w,5,t);W.evolve(b,p,w,5,t);}assert.ok(a.ice>.15);assert.ok(a.ice>b.ice+.1);});
test('snow becomes slush on thaw and residual water can refreeze',()=>{const d=make();d.select('thaw','spring');const z={...W.emptyZone(),snow:.8},p={shade:.5,drainage:.4,priority:3,phase:0};for(let t=5;t<=20;t+=5)W.evolve(z,p,d.current,5,t);assert.ok(z.snow<.8);assert.ok(z.slush>0);assert.ok(z.wet>0);for(let t=25;t<=55;t+=5)W.evolve(z,p,{...d.current,kind:'clear',tempC:-8},5,t);assert.ok(z.ice>0);});
test('public-works treatment removes snow and adds salt exactly once per slot',()=>{const d=make();d.select('snow','winter');const z={...W.emptyZone(),snow:.7,packed:.5,slush:.3},p={shade:.5,drainage:.5,priority:1,phase:0};assert.equal(W.evolve(z,p,d.current,5,60),true);assert.ok(z.snow<.3);assert.ok(z.bank>0);assert.ok(z.salt>=.72);assert.equal(z.lastService,60);assert.equal(W.evolve(z,p,d.current,0,60),false);});
test('priority roads are serviced sooner than tertiary roads',()=>{const d=make();d.select('snow','winter');const a={...W.emptyZone(),snow:.7},b={...a};for(let t=5;t<=65;t+=5){W.evolve(a,{shade:.4,drainage:.5,priority:1,phase:0},d.current,5,t);W.evolve(b,{shade:.4,drainage:.5,priority:3,phase:0},d.current,5,t);}assert.equal(a.lastService,60);assert.equal(b.lastService,-1);assert.ok(a.snow<b.snow);});
test('standing water risk depends on speed and tire health, not random spin triggers',()=>{const d=make(),z={...W.emptyZone(),wet:1,puddle:1};const slow=W.condition(z,d.current,8,20),fast=W.condition(z,d.current,32,20),healthy=W.condition(z,d.current,32,100);assert.equal(slow.hydro,0);assert.ok(fast.hydro>healthy.hydro);assert.ok(fast.grip<slow.grip);assert.ok(fast.grip>=.18);});
test('production stepCar takes longer to stop on ice, including worn brakes',()=>{
 const w=C.createWorld();w.roads=[{x1:0,z1:-10000,x2:0,z2:10000,width:12,surface:'asphalt'}];w.hash={query:()=>[]};w.bounds={minX:-10000,maxX:10000,minZ:-10000,maxZ:10000};
 function stopping(roadBrake,brakeEffect=1){const c=C.createCar(0,0,0);c.vz=-20;c.forwardSpeed=20;c.roadBrake=roadBrake;c.brakeEffect=brakeEffect;for(let i=0;i<1800&&Math.abs(c.vz)>.05;i++)C.stepCar(c,{throttle:0,brake:1,steer:0},w,C.DT,false);return c.distance;}
 const dry=stopping(1),ice=stopping(.3),worn=stopping(.3,.5);assert.ok(ice>dry*2);assert.ok(worn>ice*1.3);console.log(JSON.stringify({stoppingFromMps:20,dryM:dry,iceM:ice,wornIceM:worn}));
});
test('production throttle traction is reduced without changing legacy dry driving',()=>{const w=C.createWorld(),a=C.createCar(),b=C.createCar();b.roadDrive=.5;for(let i=0;i<120;i++){C.stepCar(a,{throttle:1},w);C.stepCar(b,{throttle:1},w);}assert.ok(a.forwardSpeed>b.forwardSpeed+1);});
test('surface observations require actual travel and are retained across reload',()=>{const d=make(),p={...world.spawn,vx:2,vz:0};const s=d.sample(p);assert.ok(s.road);assert.equal(d.observe(s,0),false);assert.equal(d.observe(s,5),true);assert.equal(d.observe(s,5),false);assert.equal(make(clone(d.state)).state.observations.length,1);});
test('nearby weather geometry remains finite, bounded and cached',()=>{const d=make();d.select('snow','winter');d.enabled=true;const a=d.props(world.spawn);assert.ok(a.length>0);assert.ok(a.length<=W.LIMITS.props);assert.equal(d.props(world.spawn),a);for(const p of a)assert.ok(['x','y','z','w','h','d','yaw'].every(k=>Number.isFinite(p[k])));d.enabled=false;assert.equal(d.props(world.spawn).length,0);});
test('town event eligibility rejects dry flooding and warm-weather plow staging',()=>{const t={...T.defaults(),minuteOfDay:480},d=make();d.select('clear','summer');assert.equal(T.eligible(T.definitions.get('flooded-shoulder'),t,d.context()),false);assert.equal(T.eligible(T.definitions.get('plow-staging'),t,d.context()),false);d.select('snow','winter');assert.equal(T.eligible(T.definitions.get('plow-staging'),t,d.context()),true);});
test('snowplow actors spawn, persist and remain under the existing actor cap',()=>{const t=new T.Director(null,world),d=make();d.select('snow','winter');for(let i=0;i<180;i++){t.tick(1,{active:true,player:world.spawn,vehicle:C.defaultVehicle(),weather:d.context()});d.advanceTo(T.now(t.state));}assert.ok(t.state.actors.some(a=>a.kind==='snowplow'));assert.ok(t.state.actors.length<=12);assert.equal(new T.Director(clone(t.state),world).state.actors.filter(a=>a.kind==='snowplow').length,t.state.actors.filter(a=>a.kind==='snowplow').length);});
test('wiper preference survives validation',()=>{const d=make();d.state.wipers=false;const s=C.validateSave({...C.validateSave(null),climate:d.state});assert.equal(s.climate.wipers,false);});
test('forged ancient cursor has bounded catch-up cost',()=>{const d=make({...W.defaults(),cursor:0},{day:999999,minuteOfDay:480,seed:995});bounded(d);assert.equal(d.state.cursor,Math.floor((999999*1440+480)/5));});
let maxBytes=0;const began=performance.now();
test('two 100-day weather runs have identical finite, bounded state including reloads',()=>{let a=make(),b=make();for(let day=0;day<100;day++){for(let m=5;m<=1440;m+=5){const t=480+day*1440+m;a.advanceTo(t);b.advanceTo(t);}bounded(a);assert.deepEqual(clone(a.state),clone(b.state));maxBytes=Math.max(maxBytes,JSON.stringify(a.state).length);if(day%10===9){const t=480+(day+1)*1440;b=make(clone(b.state),{day:Math.floor(t/1440),minuteOfDay:t%1440,seed:995});}}});
test('world, car and immutable legacy assets remain exactly unchanged',()=>{for(const [file,hash] of [['assets/worlds/north-berwick/world.json','8588954fcc6ed3c88a7336c89ea36e65213a7561e8c7a9dfdb7ad3bb7c4d0b52'],['assets/vehicles/jetta-mkiv/volkswagen-bora-jetta-mk4-2005.cc-by-4.0.glb','ac9f1d907807e5cdb0cb02beeb676f2f4ebe6c53f363d5fec3cbe183604d2e3f'],['legacy/99-5-REBORN-Build-004-PLAY.html','5ef42f30b501362aa82432b7575d90a928396639cdd672d61d2ae6f8f6caeb4f']])assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(root,file))).digest('hex'),hash);});
for(const name of ['maine-weather.js','weather-ui.js','weather-ui.css'])assert.ok(html.includes(fs.readFileSync(path.join(root,'src',name),'utf8')),name+' must be mechanically embedded');
console.log(JSON.stringify({pass:4,tests,zones:make().profiles.size,deterministicDays:100,runs:2,maxBytes,longHorizonMs:Math.round(performance.now()-began)}));
