'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.resolve(__dirname,'..'),html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const context=vm.createContext({console});
vm.runInContext([...html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi)].map(m=>m[1]).find(s=>s.includes('else root.RebornCore = api')),context);
const Guard=context.RebornCore.SessionSaves.Guard;
let tests=0;const test=async(name,fn)=>{await fn();tests++;console.log('PASS session saves: '+name);};
function storage(seed=[['save','old save'],['story','old story']]){return {data:new Map(seed),writes:0,getItem(k){return this.data.get(k)??null;},setItem(k,v){this.writes++;this.data.set(k,v);},removeItem(k){this.data.delete(k);}};}
function guard(s,known=true){return new Guard(()=>s,'save','story',s.getItem('save'),s.getItem('story'),known);}
function locks(){let occupied=false;return {async request(name,options,callback){assert.equal(name,'995.reborn.save-writer.v1');assert.equal(options.ifAvailable,true);assert.equal(options.mode,'exclusive');if(occupied)return callback(null);occupied=true;try{return await callback({name});}finally{occupied=false;}}};}
const tick=()=>new Promise(resolve=>setImmediate(resolve));
(async()=>{
 await test('the prior unguarded writer demonstrates the stale-tab overwrite',()=>{const s=storage();context.RebornCore.ReleaseUX.writePair(s,'save','story','newer save','newer story');context.RebornCore.ReleaseUX.writePair(s,'save','story','stale save','stale story');assert.equal(s.getItem('save'),'stale save');});
 await test('startup cannot write before ownership is decided',()=>{const s=storage(),g=guard(s);assert.equal(g.write('new','story').ok,false);assert.equal(s.writes,0);});
 await test('no-lock fallback retains single-tab local saving',()=>{const s=storage(),g=guard(s);g.begin(null);assert.equal(g.mode,'fallback');assert.equal(g.write('new','new story').ok,true);assert.equal(s.getItem('save'),'new');});
 await test('byte-identical repeated saves do not consume new writes',()=>{const s=storage(),g=guard(s);g.begin(null);assert.equal(g.write('old save','old story').ok,true);assert.equal(s.writes,0);});
 await test('changed save bytes block a stale writer before any write',()=>{const s=storage(),g=guard(s);g.begin(null);s.data.set('save','elsewhere');assert.equal(g.write('stale','stale').reason,'conflict');assert.equal(s.writes,0);assert.equal(s.getItem('save'),'elsewhere');});
 await test('changed story bytes independently block an old session',()=>{const s=storage(),g=guard(s);g.begin(null);s.data.set('story','chapter complete');assert.equal(g.check().reason,'conflict');assert.equal(g.write('stale','stale').ok,false);assert.equal(s.writes,0);});
 await test('clear or deletion is an external change, not permission to recreate',()=>{const s=storage(),g=guard(s);g.begin(null);s.data.clear();assert.equal(g.write('stale','stale').reason,'conflict');assert.equal(s.data.size,0);});
 await test('conflict remains latched even when bytes later match again',()=>{const s=storage(),g=guard(s);g.begin(null);s.data.set('save','elsewhere');g.check();s.data.set('save','old save');assert.equal(g.write('stale','stale').reason,'conflict');});
 await test('unknown initial read never silently treats stored data as absent',()=>{const s=storage(),g=guard(s,false);g.begin(null);assert.equal(g.write('stale','stale').reason,'unknown');assert.equal(s.writes,0);});
 await test('a throwing localStorage getter never escapes the guard',()=>{const g=new Guard(()=>{throw Error('SecurityError');},'save','story','a','b');g.begin(null);assert.equal(g.write('new','new').reason,'unavailable');});
 await test('a throwing getItem never loses the existing pair',()=>{const s=storage(),g=guard(s);g.begin(null);s.getItem=()=>{throw Error('read denied');};assert.equal(g.write('new','new').ok,false);assert.equal(s.data.get('save'),'old save');});
 await test('second-key quota failure rolls back the successful first write',()=>{const s=storage(),g=guard(s);g.begin(null);const real=s.setItem.bind(s);let calls=0;s.setItem=(k,v)=>{if(++calls===2)throw Error('quota');real(k,v);};const r=g.write('new','new story');assert.equal(r.ok,false);assert.equal(r.restored,true);assert.equal(s.getItem('save'),'old save');assert.equal(s.getItem('story'),'old story');});
 await test('failed restore keeps the previous recovery copy as well as both saves',()=>{const s=storage(),g=guard(s);s.data.set('recovery','prior recovery');g.begin(null);const real=s.setItem.bind(s);let calls=0;s.setItem=(k,v)=>{if(++calls===3)throw Error('quota');real(k,v);};const r=g.write('restored','restored story',{key:'recovery',text:'new recovery'});assert.equal(r.restored,true);assert.equal(s.getItem('recovery'),'prior recovery');assert.equal(s.getItem('save'),'old save');assert.equal(s.getItem('story'),'old story');});
 await test('absent recovery key is removed on rollback, not replaced with a string null',()=>{const s=storage(),g=guard(s);g.begin(null);const real=s.setItem.bind(s);let calls=0;s.setItem=(k,v)=>{if(++calls===3)throw Error('quota');real(k,v);};assert.equal(g.write('new','new',{key:'recovery',text:'backup'}).restored,true);assert.equal(s.getItem('recovery'),null);});
 await test('rollback does not clobber a third-party value appearing after the first write',()=>{const s=storage(),g=guard(s);g.begin(null);s.setItem=(k,v)=>{if(k==='story'){s.data.set('save','external winner');throw Error('quota');}s.data.set(k,v);};const r=g.write('new','new');assert.equal(r.ok,false);assert.equal(r.restored,false);assert.equal(g.conflict,true);assert.equal(s.getItem('save'),'external winner');});
 await test('successful restore preserves raw empty and absent records exactly',()=>{const s=storage([['save','']]),g=guard(s);g.begin(null);const r=g.write('valid save','valid story',{key:'recovery',text:JSON.stringify({save:'',story:null})});assert.equal(r.ok,true);assert.deepEqual(JSON.parse(s.getItem('recovery')),{save:'',story:null});});
 await test('only one cooperating tab receives save ownership',async()=>{const s=storage(),a=guard(s),b=guard(s),l=locks();a.begin(l);b.begin(l);await tick();assert.equal(a.mode,'owner');assert.equal(b.mode,'other');assert.equal(a.write('owner save','owner story').ok,true);assert.equal(b.write('other save','other story').reason,'other');assert.equal(s.getItem('save'),'owner save');a.release();await tick();assert.equal(b.mode,'other');});
 await test('closing owner allows a newly loaded session, not a stale waiting tab',async()=>{const s=storage(),a=guard(s),l=locks();a.begin(l);await tick();a.write('owner save','owner story');a.release();await tick();const b=guard(s);b.begin(l);await tick();assert.equal(b.mode,'owner');assert.equal(b.write('next save','next story').ok,true);b.release();});
 await test('late lock grant after pagehide cannot resurrect an obsolete writer',async()=>{const s=storage(),g=guard(s);let callback;g.begin({request(n,o,cb){callback=cb;return Promise.resolve();}});g.release();await callback({name:'late'});assert.equal(g.mode,'released');assert.equal(g.write('new','new').ok,false);});
 await test('BFCache-like reacquisition rechecks bytes before restoring write access',async()=>{const s=storage(),g=guard(s),l=locks();g.begin(l);await tick();g.release();await tick();s.data.set('save','new owner data');g.begin(l);await tick();assert.equal(g.conflict,true);assert.equal(g.write('old RAM','old story').ok,false);g.release();});
 await test('lock acquisition failure is session-only, not an unsafe fallback',async()=>{const s=storage(),g=guard(s);g.begin({request(){return Promise.reject(Error('denied'));}});await tick();assert.equal(g.mode,'unavailable');assert.equal(g.write('new','new').ok,false);assert.equal(s.writes,0);});
 await test('successful writes advance the expected raw pair for repeated autosaves',()=>{const s=storage(),g=guard(s);g.begin(null);for(let i=0;i<200;i++)assert.equal(g.write('save '+i,'story '+i).ok,true);assert.equal(g.check().ok,true);assert.equal(s.getItem('save'),'save 199');});
 console.log(JSON.stringify({pass:9,sessionSaveChecks:tests,result:'passed',fallbackIsTransaction:false}));
})().catch(error=>{console.error(error);process.exitCode=1;});
