(()=>{'use strict';
const $=id=>document.getElementById(id);const root=document.body;
function snap(){try{return window.REBORN?.snapshot?.()||{};}catch(e){return {error:String(e)}}}
function report(){const s=snap(),g=s.graphics||{},r=s.release||{};return {format:'REBORN_FRAME_PACER_REPORT_V1',createdAt:new Date().toISOString(),version:window.REBORN?.version||'unknown',state:s.appState,renderer:s.renderer,fps:s.fps,resolutionScale:s.resolutionScale,renderTier:s.renderTier,canvasPixels:s.canvasPixels,framePacer:{enabled:!!r.framePacer,cap:r.frameCap,intervalMs:r.frameIntervalMs,mode:r.frameMode,jitterMs:r.frameJitterMs,renderedFrames:r.renderedFrames,skippedFrames:r.skippedRenderFrames},graphics:{drawCalls:g.drawCalls,triangles:g.triangles,instances:g.instances,culledInstances:g.culledInstances,renderBudgetPixels:g.renderBudgetPixels,renderDprCap:g.renderDprCap,visualRange:g.visualRange,shadowCadence:g.shadowCadence,bloomCadence:g.bloomCadence,probeCadence:g.probeCadence,contextLost:g.contextLost,contextLosses:g.contextLosses,contextRecoveries:g.contextRecoveries,renderOptimizer:g.renderOptimizer,visualUpgrade:g.visualUpgrade},car:s.car,viewport:{width:innerWidth,height:innerHeight,dpr:devicePixelRatio||1,coarse:matchMedia('(pointer:coarse)').matches,userAgent:navigator.userAgent},errors:s.errors||[]};}
function download(name,text,type='application/json'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;document.body.append(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove();},1500);}
function copy(text){return navigator.clipboard?.writeText(text).catch(()=>{})}
function ensure(){if($('frame-pacer-panel'))return;const d=document.createElement('dialog');d.id='frame-pacer-panel';d.innerHTML='<form method="dialog" class="modal"><div class="modal-kicker">FRAME PACER</div><h2>Adaptive desktop/mobile frame pacing</h2><p class="modal-sub">Local-only report for render cadence, skipped frames, canvas budget and graphics recovery state. Nothing is uploaded.</p><pre id="frame-pacer-readout" style="white-space:pre-wrap;max-height:45vh;overflow:auto"></pre><div class="result-actions"><button id="frame-pacer-copy" type="button" class="secondary">COPY JSON</button><button id="frame-pacer-download" type="button" class="secondary">DOWNLOAD JSON</button><button value="close" class="primary">CLOSE</button></div></form>';root.append(d);$('frame-pacer-copy').addEventListener('click',()=>copy(JSON.stringify(report(),null,2)));$('frame-pacer-download').addEventListener('click',()=>download('REBORN-frame-pacer-report.json',JSON.stringify(report(),null,2)));}
function open(){ensure();$('frame-pacer-readout').textContent=JSON.stringify(report(),null,2);$('frame-pacer-panel').showModal();}
function button(){if($('frame-pacer-button'))return;const hud=$('hud')||root;const b=document.createElement('button');b.id='frame-pacer-button';b.type='button';b.textContent='FRAME';b.className='secondary';b.style.cssText='position:fixed;right:1rem;bottom:18rem;z-index:20';b.addEventListener('click',open);hud.append(b);}
window.addEventListener('keydown',e=>{if(e.target?.matches?.('input,textarea,select,[contenteditable=true],dialog *'))return;if(e.code==='KeyL'){e.preventDefault();open();}});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',button);else button();
window.REBORN_FRAME_PACER={report,open};
})();
