// Presentation and navigation only. Fixed-step simulation and save identity stay intact.
let uxMapCenter=null,uxMapView=null,uxDestination=null,uxLastWorld=null,uxTab='overview';
const uxModeNames={free:'Free drive',run:'Harbor run',pursuit:'Lose the tail',arena:'Breaker yard'};
function setUXSaveStatus(ok){const node=$('ux-save');if(node){node.textContent=ok?'●  LOCAL SAVE READY':'SAVE UNAVAILABLE · SESSION ONLY';node.dataset.error=String(!ok);}}
function applyDriverPreferences(){document.body.dataset.hud=settings.hudStyle||'full';document.body.dataset.contrast=settings.highContrast?'high':'normal';document.body.dataset.hints=settings.controlHints===false?'off':'on';document.body.dataset.motion=settings.reducedMotion?'reduced':'normal';for(const [id,value] of [['ux-units',settings.units||'mph'],['ux-hud',settings.hudStyle||'full'],['ux-camera',String(cameraStyle)]])if($(id))$(id).value=value;if($('ux-contrast'))$('ux-contrast').checked=!!settings.highContrast;if($('ux-hints'))$('ux-hints').checked=settings.controlHints!==false;if($('ux-volume')){$('ux-volume').value=Math.round((settings.volume??1)*100);$('ux-volume-value').textContent=$('ux-volume').value+'%';}}
function updateDriverHUD(){const speed=Math.hypot(sim.car.vx,sim.car.vz);if(settings.units==='kph'){$('speed').textContent=String(Math.round(speed*3.6)).padStart(3,'0');$('gear').querySelector('b').textContent='KM/H';$('temp-value').textContent=Math.round(vehicle.engineTempC)+'°C';}const warnings=[];if(vehicle.fuel<15)warnings.push(vehicle.fuel<.1?'Out of fuel':'Low fuel');if(vehicle.engineTempC>=108)warnings.push('Engine overheating');if(sim.car.health<30)warnings.push('Body condition critical');if(vehicle.brakes<30)warnings.push('Brake wear critical');if(vehicle.tires<30)warnings.push('Tire wear critical');if(vehicle.battery<=18)warnings.push('Low battery');$('ux-alert').textContent=warnings.join(' · ');$('ux-alert').hidden=!warnings.length;
 const available=uxDestination&&sim.world===uxLastWorld&&sim.mode==='free'&&!director.active;$('ux-navigation').hidden=!available;if(available){const dx=uxDestination.x-sim.car.x,dz=uxDestination.z-sim.car.z,metres=Math.hypot(dx,dz),heading=(Math.atan2(dx,-dz)*180/Math.PI+360)%360;const distance=settings.units==='kph'?(metres/1000).toFixed(1)+' km':(metres/1609.344).toFixed(1)+' mi';$('ux-navigation').textContent=metres<35?uxDestination.name+' · Nearby':uxDestination.name+' · '+distance+' · bearing '+Math.round(heading)+'°';$('ux-navigation').title='Straight-line bearing only, not a routed driving instruction.';}
 $('ux-driving-tip').hidden=state!=='play'||settings.tutorialSeen||settings.controlHints===false||!!director.active||!!townDirector?.nearest(sim.car);$('pulse-button').disabled=sim.car.mode!=='reborn'||sim.car.pulseCooldown>0||sim.car.energy<30;
}
function updateDriverState(){applyDriverPreferences();setUXSaveStatus(storageAvailable);if(uxLastWorld&&uxLastWorld!==sim.world){uxDestination=null;uxMapCenter=null;uxLastWorld=null;}const blocking=['pause','map','journey','town','story','result'].includes(state);for(const id of ['intro','hud','inspection'])$(id).inert=blocking;for(const id of ['pause','map-overlay','journey','town-dialog','story','result'])$(id).inert=$(id).hidden;if(state==='menu'){const unit=settings.units==='kph'?'km':'mi',odo=vehicle.odometerMiles*(settings.units==='kph'?1.609344:1);$('ux-garage-summary').innerHTML='<span><b>'+odo.toFixed(1)+'</b>ODOMETER / '+unit.toUpperCase()+'</span><span><b>'+Math.round(vehicle.fuel)+'%</b>FUEL RESERVE</span><span><b>'+Object.keys(roadKnowledge).length+'</b>ROADS REMEMBERED</span>';}$('ux-driving-tip').hidden=state!=='play'||settings.tutorialSeen||settings.controlHints===false;if(state==='map'){updateMapSearch();drawExpandedMap();}if(state==='journey')selectDriverTab(uxTab);}
function selectDriverTab(name,focus=false){if(!['overview','workshop','town','journal'].includes(name))name='overview';uxTab=name;for(const tab of document.querySelectorAll('[data-ux-tab]')){const active=tab.dataset.uxTab===name;tab.setAttribute('aria-selected',String(active));tab.tabIndex=active?0:-1;if(active&&focus)tab.focus();}for(const panel of document.querySelectorAll('.ux-tab-panel'))panel.hidden=panel.id!=='ux-panel-'+name;}
function updateMapSearch(){const value=$('ux-map-search').value.trim().toLowerCase(),list=$('ux-map-results');list.replaceChildren();if(!value)return;const world=sim.world,seen=new Set(),entries=[...(world.landmarks||[]),...(world.roadLabels||[])].filter(p=>typeof p.name==='string'&&Number.isFinite(p.x)&&Number.isFinite(p.z)&&p.name.toLowerCase().includes(value));for(const item of entries){if(seen.has(item.name))continue;seen.add(item.name);const button=document.createElement('button');button.type='button';button.textContent=item.name;button.addEventListener('click',()=>{uxDestination={x:item.x,z:item.z,name:item.name};uxLastWorld=world;uxMapCenter={x:item.x,z:item.z};setMapZoom(24);drawExpandedMap();$('ux-clear-pin').disabled=false;$('ux-map-search').value=item.name;list.replaceChildren();$('expanded-map').focus();});list.append(button);if(seen.size>=8)break;}if(!seen.size){const note=document.createElement('span');note.textContent='No matching places. Try a road or public landmark.';list.append(note);}}
function drawDriverMap(ctx,p){if(!uxDestination||sim.world!==uxLastWorld)return;const[x,y]=p(uxDestination.x,uxDestination.z);ctx.save();ctx.strokeStyle='#8bd5bf';ctx.fillStyle='#8bd5bf';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,9,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.arc(x,y,3,0,Math.PI*2);ctx.fill();ctx.font='600 13px Arial';ctx.fillText(uxDestination.name,x+13,y-10);ctx.restore();}
function initDriverUX(){
 const settingsBody=document.createElement('div');settingsBody.className='ux-settings-body';const settingsList=document.querySelector('#pause .settings');settingsList.before(settingsBody);settingsBody.append(settingsList,document.querySelector('#pause .control-help'),$('renderer-info'));
 $('pause').insertAdjacentHTML('beforeend','<button id="ux-close-settings" type="button" aria-label="Close settings and return. Escape.">×</button>');$('ux-close-settings').addEventListener('click',resume);
 $('journey-open').textContent='JETTA HUB ↗';$('journey-open').setAttribute('aria-label','Jetta hub: condition, workshop, living town and road journal');
 $('intro').insertAdjacentHTML('afterbegin','<div id="ux-save" class="ux-save" role="status" aria-live="polite"></div>');document.querySelector('.intro-copy').insertAdjacentHTML('beforeend','<div id="ux-garage-summary" aria-label="Jetta quick status"></div>');
 $('hud').insertAdjacentHTML('beforeend','<div id="ux-navigation" hidden></div><div id="ux-alert" role="status" aria-live="polite" hidden></div><button id="ux-map-button" type="button">M · OPEN MAP</button><aside id="ux-driving-tip" hidden aria-label="Driving quick start"><strong>Your road. Your pace.</strong><span id="ux-tip-text"></span><button id="ux-dismiss-tip" class="secondary" type="button">GOT IT · LET’S DRIVE</button></aside>');
 $('ux-tip-text').textContent=touch?'Stick up to drive, down to brake or reverse. Left and right steer. Tap the map to explore.':'W / ↑ to accelerate. S / ↓ to brake or reverse. A/D steer. M opens the map. C changes the camera.';
 $('ux-dismiss-tip').addEventListener('click',()=>{settings.tutorialSeen=true;$('ux-driving-tip').hidden=true;persist();$('pause-button').focus();});$('ux-map-button').addEventListener('click',openMap);
 document.querySelector('#pause .settings').insertAdjacentHTML('beforeend','<label><span>Instrument units <small>HUD only · journal records retain miles</small></span><select id="ux-units"><option value="mph">MPH / °F</option><option value="kph">KM/H / °C</option></select></label><label><span>Driving HUD <small>Critical warnings remain visible in both modes</small></span><select id="ux-hud"><option value="full">Full instruments</option><option value="minimal">Minimal / focus</option></select></label><label><span>Camera</span><select id="ux-camera"><option value="0">Third person</option><option value="1">Wide third person</option><option value="2">Inside the Jetta</option></select></label><label><span>High-contrast instruments</span><input id="ux-contrast" type="checkbox"></label><label><span>Control hints</span><input id="ux-hints" type="checkbox"></label>');
 document.querySelector('#pause .modal-buttons').insertAdjacentHTML('beforeend','<button id="ux-fullscreen" type="button" class="secondary">TOGGLE FULLSCREEN</button><button id="ux-show-guide" type="button" class="secondary">SHOW DRIVING GUIDE</button>');
 for(const [id,key] of [['ux-units','units'],['ux-hud','hudStyle'],['ux-contrast','highContrast'],['ux-hints','controlHints']])$(id).addEventListener('change',()=>{settings[key]=$(id).type==='checkbox'?$(id).checked:$(id).value;applyDriverPreferences();persist();});
 $('ux-camera').addEventListener('change',()=>{cameraStyle=Number($('ux-camera').value);cameraEye=null;cameraTarget=null;updateCameraChoice();});$('ux-fullscreen').addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch(_){notify('FULLSCREEN UNAVAILABLE IN THIS BROWSER');}});$('ux-show-guide').addEventListener('click',()=>{settings.tutorialSeen=false;settings.controlHints=true;persist();applyDriverPreferences();notify('DRIVING GUIDE ENABLED FOR YOUR NEXT DRIVE');});
 document.querySelector('#pause .settings').insertAdjacentHTML('beforeend','<label for="ux-volume"><span>Engine & effects volume <output id="ux-volume-value">100%</output></span><input id="ux-volume" type="range" min="0" max="100" step="5"></label>');$('ux-volume').value=Math.round((settings.volume??1)*100);$('ux-volume-value').textContent=$('ux-volume').value+'%';$('ux-volume').addEventListener('input',()=>{settings.volume=Number($('ux-volume').value)/100;audio.volume=settings.volume;audio.setEnabled(settings.sound);$('ux-volume-value').textContent=$('ux-volume').value+'%';});$('ux-volume').addEventListener('change',persist);
 $('ux-fullscreen').insertAdjacentHTML('afterend','<button id="ux-export-save" type="button" class="secondary">EXPORT SAVE BACKUP</button>');$('ux-export-save').addEventListener('click',()=>{const data=JSON.stringify({format:'REBORN_BACKUP_V1',exportedAt:new Date().toISOString(),save:C.validateSave(save),story:S.validateProgress(director.progress)},null,2),url=URL.createObjectURL(new Blob([data],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='REBORN-save-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
 const grid=document.querySelector('.journey-grid'),tabs=document.createElement('nav');tabs.className='ux-tabs';tabs.setAttribute('role','tablist');tabs.setAttribute('aria-label','Jetta hub');grid.before(tabs);
 const sections={overview:['vehicle-condition-grid','symptom-list'],workshop:['diagnostic-tests','parts-grid','repair-history'],town:['town-ledger'],journal:['road-memory-summary','drive-journal']};for(const [name,ids]of Object.entries(sections)){const button=document.createElement('button');button.type='button';button.id='ux-tab-'+name;button.dataset.uxTab=name;button.setAttribute('role','tab');button.setAttribute('aria-controls','ux-panel-'+name);button.textContent={overview:'Jetta status',workshop:'Workshop',town:'Living town',journal:'Road journal'}[name];button.addEventListener('click',()=>selectDriverTab(name));tabs.append(button);const panel=document.createElement('div');panel.id='ux-panel-'+name;panel.className='ux-tab-panel';panel.setAttribute('role','tabpanel');panel.setAttribute('aria-labelledby',button.id);for(const id of ids)panel.append($(id).closest('.journey-panel'));grid.append(panel);}
 tabs.addEventListener('keydown',e=>{const list=Array.from(tabs.querySelectorAll('button')),index=list.indexOf(document.activeElement);let next=index;if(e.key==='ArrowRight')next=(index+1)%list.length;else if(e.key==='ArrowLeft')next=(index+list.length-1)%list.length;else if(e.key==='Home')next=0;else if(e.key==='End')next=list.length-1;else return;e.preventDefault();e.stopPropagation();selectDriverTab(list[next].dataset.uxTab,true);});selectDriverTab('overview');
 const canvas=$('expanded-map');canvas.setAttribute('tabindex','0');canvas.setAttribute('aria-label','Road map. Drag or use arrow keys to pan. Plus and minus zoom. Search to pin a landmark.');canvas.before(Object.assign(document.createElement('div'),{className:'ux-map-toolbar',innerHTML:'<label for="ux-map-search">FIND A PLACE<input id="ux-map-search" type="search" placeholder="Road or landmark…" autocomplete="off"></label><button id="ux-map-recenter" type="button" class="secondary">MY CAR</button><button id="ux-map-fit" type="button" class="secondary">WHOLE TOWN</button><button id="ux-clear-pin" type="button" class="secondary" disabled>CLEAR PIN</button>'}));canvas.before(Object.assign(document.createElement('div'),{id:'ux-map-results',className:'ux-map-results'}));canvas.after(Object.assign(document.createElement('div'),{className:'ux-map-legend',innerHTML:'<span>Your car</span><span>Incident / reduced lane</span><span>Pinned place · straight-line bearing, not a route</span>'}));$('ux-map-results').setAttribute('aria-live','polite');
 $('ux-map-search').addEventListener('input',updateMapSearch);$('ux-map-recenter').addEventListener('click',()=>{uxMapCenter={x:sim.car.x,z:sim.car.z};setMapZoom(24);drawExpandedMap();});$('ux-map-fit').addEventListener('click',()=>{uxMapCenter=null;setMapZoom(1);drawExpandedMap();});$('ux-clear-pin').addEventListener('click',()=>{uxDestination=null;$('ux-clear-pin').disabled=true;$('ux-map-search').value='';updateMapSearch();drawExpandedMap();});
 const pointers=new Map();let pinch=0;canvas.addEventListener('pointerdown',e=>{e.preventDefault();pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});canvas.setPointerCapture(e.pointerId);canvas.focus();if(pointers.size===2){const[a,b]=[...pointers.values()];pinch=Math.hypot(a.x-b.x,a.y-b.y);}});canvas.addEventListener('pointermove',e=>{const old=pointers.get(e.pointerId);if(!old||!uxMapView)return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2){const[a,b]=[...pointers.values()],distance=Math.hypot(a.x-b.x,a.y-b.y);if(pinch>0)setMapZoom(mapZoom*distance/pinch);pinch=distance;return;}const rect=canvas.getBoundingClientRect(),scale=uxMapView.scale;uxMapCenter={x:uxMapView.centerX-(e.clientX-old.x)*canvas.width/rect.width/scale,z:uxMapView.centerZ+(e.clientY-old.y)*canvas.height/rect.height/scale};clampMapCenter();drawExpandedMap();});for(const event of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(event,e=>{pointers.delete(e.pointerId);pinch=0;});
 canvas.addEventListener('keydown',e=>{if(e.key==='+'||e.key==='=')changeMapZoom(1);else if(e.key==='-')changeMapZoom(-1);else if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)&&uxMapView){const step=100/uxMapView.scale;uxMapCenter={x:uxMapView.centerX+(e.key==='ArrowRight'?step:e.key==='ArrowLeft'?-step:0),z:uxMapView.centerZ+(e.key==='ArrowUp'?step:e.key==='ArrowDown'?-step:0)};clampMapCenter();drawExpandedMap();}else return;e.preventDefault();e.stopPropagation();});
 window.addEventListener('resize',()=>{if(state==='map')drawExpandedMap();});
 const mini=$('minimap');mini.tabIndex=0;mini.setAttribute('role','button');mini.setAttribute('aria-label','Open paused road map. M.');mini.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();e.stopPropagation();openMap();}});
 document.addEventListener('keydown',e=>{const id={map:'map-overlay',journey:'journey',town:'town-dialog',pause:'pause',story:'story',result:'result'}[state];if(!id)return;if(e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();if(state==='map')closeMap();else if(state==='journey')closeJourney();else if(state==='town')closeTown();else if(state==='pause')resume();else if(state==='story')$('story-back').click();else garage();return;}if(e.key==='Tab'){const controls=Array.from($(id).querySelectorAll('button:not([disabled]),input:not([disabled]),select,[tabindex="0"]')).filter(x=>x.offsetParent!==null&&!x.hidden&&x.tabIndex>=0&&!x.disabled);if(!controls.length)return;const first=controls[0],last=controls.at(-1);if(!$(id).contains(document.activeElement)){first.focus();e.preventDefault();e.stopImmediatePropagation();}else if(e.shiftKey&&document.activeElement===first){last.focus();e.preventDefault();e.stopImmediatePropagation();}else if(!e.shiftKey&&document.activeElement===last){first.focus();e.preventDefault();e.stopImmediatePropagation();}}},true);
 for(const b of document.querySelectorAll('[data-mode]'))b.addEventListener('click',()=>{$('drive').setAttribute('aria-label','Take the wheel: '+uxModeNames[b.dataset.mode]);});
}
function clampMapCenter(){if(!uxMapCenter)return;const b=sim.world.bounds;uxMapCenter.x=C.clamp(uxMapCenter.x,b.minX,b.maxX);uxMapCenter.z=C.clamp(uxMapCenter.z,b.minZ,b.maxZ);}
// Reserve label rectangles so the town center stays legible at every zoom level.
function drawDriverMapLabels(ctx,p,world,w,h,pad){
 const occupied=[];
 const label=(text,x,y,color,font)=>{ctx.font=font;const width=ctx.measureText(text).width;if(x<pad||x>w-pad||y<pad+14||y>h-pad)return;const left=Math.max(pad+3,Math.min(x+7,w-pad-width-3)),box={left,right:left+width+6,top:y-13,bottom:y+4};if(occupied.some(r=>r.left<box.right&&r.right>box.left&&r.top<box.bottom&&r.bottom>box.top))return;occupied.push(box);ctx.strokeStyle='#10252b';ctx.lineWidth=3;ctx.strokeText(text,left,y);ctx.fillStyle=color;ctx.fillText(text,left,y);};
 if(uxDestination){const[x,y]=p(uxDestination.x,uxDestination.z);ctx.font='600 13px Arial';occupied.push({left:x+10,right:x+16+ctx.measureText(uxDestination.name).width,top:y-26,bottom:y-5});}
 const landmarks=[...world.landmarks].sort((a,b)=>Math.hypot(a.x-uxMapView.centerX,a.z-uxMapView.centerZ)-Math.hypot(b.x-uxMapView.centerX,b.z-uxMapView.centerZ));
 for(const item of landmarks){const[x,y]=p(item.x,item.z);ctx.fillStyle='#efc887';ctx.fillRect(x-2,y-2,4,4);if(item.name!==uxDestination?.name)label(item.name,x,y,'#efc887','600 12px Arial');}
 const seen=new Set();for(const item of world.roadLabels){if(!world.priorityRoadNames.includes(item.name)||seen.has(item.name))continue;seen.add(item.name);const[x,y]=p(item.x,item.z);label(item.name,x,y,'#a7bdb7','11px Arial');}
}
