// Embedded in the existing application closure; no runtime imports.
const townClockText=s=>'DAY '+(s.day+1)+' · '+String(Math.floor(s.minuteOfDay/60)).padStart(2,'0')+':'+String(Math.floor(s.minuteOfDay%60)).padStart(2,'0')+' · '+C.Town.band(s.minuteOfDay);
function townAvailable(){return !!townDirector&&!!sim.world.northBerwick&&sim.mode==='free'&&!director.active;}
function updateTownHUD(){const active=townAvailable();$('town-clock').hidden=!active;const e=active?townDirector.nearest(sim.car):null;$('town-interact').hidden=!e;if(active)$('town-clock').textContent=townClockText(townDirector.state);if(e)$('town-interact').textContent='F · '+C.Town.definitions.get(e.type).title+(Math.hypot(sim.car.vx,sim.car.vz)>1.5?' · STOP FIRST':' · INTERACT');}
function townMessages(){const messages=townDirector.takeMessages();if(!messages.length)return;for(const m of messages)appendJournal({id:'town-'+(++save.stats.sequence),kind:'town',endedAt:new Date().toISOString(),mode:'free',world:'North Berwick',reason:m.title+': '+m.text,seconds:0,miles:0,roads:0,startRoad:m.road,endRoad:m.road,fuelUsed:0,bodyLoss:0,maxMph:0});persist();}
function tickTown(dt){if(!townDirector)return;townDirector.tick(dt,{active:state==='play'&&townAvailable(),player:sim.car,vehicle,weather:settings.weather});townMessages();}
function openTown(){if(state!=='play'||!townAvailable())return;const e=townDirector.nearest(sim.car);if(!e)return;if(Math.hypot(sim.car.vx,sim.car.vz)>1.5){notify('STOP SAFELY BEFORE INTERACTING');return;}townEventId=e.id;state='town';input.clear();accumulator=0;const d=C.Town.definitions.get(e.type);$('town-title').textContent=d.title;$('town-situation').textContent=d.description+' '+e.location.road+' · '+d.risk;$('town-choices').innerHTML=C.Town.choices(e,vehicle).map(c=>'<button type="button" class="secondary" data-town-choice="'+c.id+'" '+(c.disabled?'disabled':'')+'><strong>'+safeText(c.label)+'</strong><span>'+safeText(c.effect)+'</span></button>').join('');showState();$('town-choices').querySelector('button:not([disabled])')?.focus();}
function closeTown(){if(state!=='town')return;state='play';input.clear();accumulator=0;townEventId=null;showState();updateHUD();}
function renderTownLedger(){const s=townDirector?.state||save.town,html=['<p>'+safeText(townClockText(s))+' · TRUST '+Math.round(s.trust)+'/100</p><p>Fictional gameplay schedules, not real opening hours. Clock pauses in menus.</p>'];html.push('<p>Helped '+s.stats.helped+' · Calls '+s.stats.called+' · Ignored '+s.stats.ignored+' · Failed '+s.stats.failed+' · Assistance received '+s.stats.assistance+'</p>');html.push('<h4>ACTIVE INCIDENTS / AMBER MAP DOTS</h4>');for(const e of s.activeEvents)html.push('<p>'+safeText(C.Town.definitions.get(e.type).title)+' — '+safeText(e.location.road)+' · '+safeText(e.state)+' · '+Math.max(0,Math.ceil(e.expires-C.Town.now(s)))+' town minutes remaining</p>');if(!s.activeEvents.length)html.push('<p>No active incidents. Explore North Berwick Free Drive.</p>');html.push('<h4>REDUCED LANES / AMBER MAP LINES</h4>');for(const c of s.closures){const e=s.activeEvents.find(e=>e.id===c.id);html.push('<p>'+safeText(e?.location.road||'Road')+' · opposite lane remains open · clears in '+Math.ceil(c.until-C.Town.now(s))+' town minutes</p>');}if(!s.closures.length)html.push('<p>No reduced lanes.</p>');html.push('<h4>PUBLIC SERVICE / TRAFFIC</h4><p>'+safeText(s.actors.map(a=>a.kind+' on '+a.location.road).join(' · ')||'No scheduled actors nearby in town state.')+'</p><h4>UNRESOLVED CONSEQUENCES</h4>');for(const c of s.consequences)html.push('<p>'+safeText(c.kind)+' · '+safeText(c.road)+' · '+Math.ceil(c.until-C.Town.now(s))+' town minutes</p>');html.push('<h4>RECENT RESOLVED INCIDENTS</h4>');for(const e of s.resolvedEvents.slice(0,12))html.push('<p>'+safeText(C.Town.definitions.get(e.type).title)+' · '+safeText(e.state)+' · '+safeText(e.road)+'</p>');html.push('<h4>EVENT HISTORY / FUTURE SUPPORT</h4>');for(const e of s.history.slice(0,16))html.push('<p>'+safeText(e.road)+' · '+safeText(e.text)+'</p>');$('town-ledger').innerHTML=html.join('');}
function drawTownMap(ctx,p){if(!townAvailable())return;ctx.save();ctx.strokeStyle='#ffc875';ctx.fillStyle='#ffc875';ctx.lineWidth=4;for(const c of townDirector.state.closures){const r=townDirector.network.roads.get(c.roadId);if(!r)continue;ctx.beginPath();ctx.moveTo(...p(r.x1,r.z1));ctx.lineTo(...p(r.x2,r.z2));ctx.stroke();}for(const e of townDirector.state.activeEvents){ctx.beginPath();ctx.arc(...p(e.location.x,e.location.z),5,0,Math.PI*2);ctx.fill();}ctx.restore();}
$('town-interact').addEventListener('click',openTown);$('town-close').addEventListener('click',closeTown);
$('town-choices').addEventListener('click',event=>{const b=event.target.closest('[data-town-choice]');if(!b||b.disabled)return;const result=townDirector.interact(townEventId,b.dataset.townChoice,vehicle,sim.car);if(!result.ok){notify(result.reason||'ACTION UNAVAILABLE');return;}townMessages();closeTown();});
$('town-dialog').addEventListener('keydown',event=>{if(event.key==='Tab'){const buttons=Array.from($('town-dialog').querySelectorAll('button:not([disabled])'));const first=buttons[0],last=buttons.at(-1);if(event.shiftKey&&document.activeElement===first){last.focus();event.preventDefault();}else if(!event.shiftKey&&document.activeElement===last){first.focus();event.preventDefault();}}});
